# Generated by Django 5.2.1 on 2025-11-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=64)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='msuTracking.meal')),
            ],
        ),
    ]
