# Generated by Django 5.2.1 on 2025-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msuTracking', '0002_day_alter_fooddata_id_alter_meal_id_alter_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
