# Generated by Django 5.2.1 on 2025-11-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msuTracking', '0003_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
