# Generated by Django 5.2.1 on 2025-11-08 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msuTracking', '0004_alter_meal_meal_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='msuTracking.meal'),
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=64),
        ),
    ]
